config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dianagudu/motley_cue:
      branch: master
      repo: https://github.com/dianagudu/motley_cue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dianagudu/motley_cue git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-xanthic-raccoon.sh
        container: qc.acc_surly-orchid-falcon
  QC.Doc:
    repos:
      github.com/dianagudu/motley_cue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-ecru-otter.sh
        container: qc.doc_gummy-ruby-camel
      github.com/dianagudu/motley_cue git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-malachite-slug.sh
        container: qc.doc_whiny-linen-anteater
      github.com/dianagudu/motley_cue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-olivine-maltese.sh
        container: qc.doc_wimpy-aqua-nightingale
      github.com/dianagudu/motley_cue restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-buff-lobster.sh
        container: qc.doc_wiggy-cerulean-kangaroo
  QC.Lic:
    repos:
      github.com/dianagudu/motley_cue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-maroon-bee.sh
        container: qc.lic_boozy-vermilion-cuscus
  QC.Sec:
    repos:
      github.com/dianagudu/motley_cue bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-xanthic-tapir.sh
        container: qc.sec_fuzzy-harlequin-macaw
  QC.Sty:
    repos:
      github.com/dianagudu/motley_cue flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-myrtle-heron.sh
        container: qc.sty_bumpy-teal-llama
      github.com/dianagudu/motley_cue rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-magenta-hyena.sh
        container: qc.sty_tasty-russet-gerbil
  QC.Ver:
    repos:
      github.com/dianagudu/motley_cue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sangria-paradise.sh
        container: qc.ver_baggy-chestnut-shrimp
timeout: 1800
