config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dianagudu/motley_cue:
      branch: master
      repo: https://github.com/dianagudu/motley_cue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dianagudu/motley_cue git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-violet-rhinoceros.sh
        container: qc.acc_gloppy-ultramarine-hyena
  QC.Doc:
    repos:
      github.com/dianagudu/motley_cue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-platinum-deer.sh
        container: qc.doc_lanky-maroon-coyote
      github.com/dianagudu/motley_cue git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-wheat-lizard.sh
        container: qc.doc_boozy-silver-snail
      github.com/dianagudu/motley_cue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-burgundy-wildebeest.sh
        container: qc.doc_paltry-persimmon-slug
      github.com/dianagudu/motley_cue restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-gold-jackal.sh
        container: qc.doc_craggy-lemon-blue
  QC.Lic:
    repos:
      github.com/dianagudu/motley_cue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-celadon-peccary.sh
        container: qc.lic_boozy-amethyst-frog
  QC.Sec:
    repos:
      github.com/dianagudu/motley_cue bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-purple-cockroach.sh
        container: qc.sec_sleepy-ruby-spider
  QC.Sty:
    repos:
      github.com/dianagudu/motley_cue flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-sangria-anteater.sh
        container: qc.sty_ugly-periwinkle-foxhound
  QC.Ver:
    repos:
      github.com/dianagudu/motley_cue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-bronze-pinscher.sh
        container: qc.ver_fuzzy-purple-binturong
timeout: 1800
